"""
Project Name : Retail Sales Exploratory Data Analysis (EDA)

Tools Used:
- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

Objective:
To analyze retail sales data, identify sales trends,
customer behavior, payment preferences, and provide
business insights using Exploratory Data Analysis.

Author: Your Name
"""

print("==========================================================")
print("Exploratory Data Analysis (EDA)")
print("==========================================================\n")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Clean Dataset
data = pd.read_csv("Retail_Sales_Cleaned.csv")
print(data.head(5))


'Step 1: Dataset Overview (KPI Analysis)'

print("\n" + "="*50)
print("RETAIL SALES DATASET OVERVIEW")
print("="*50)

print(f"\nTotal Orders      : {data['Order_ID'].nunique()}")
print(f"Total Customers   : {data['Customer_ID'].nunique()}")
print(f"Total Sales       : ₹{data['Total_Sales'].sum():,.2f}")
print(f"Average Order     : ₹{data['Total_Sales'].mean():,.2f}")
print(f"Average Rating    : {data['Rating'].mean():.2f}\n")



'Category-wise Sales'

print("\n" + "="*60)
print("Category-wise Sales")
print("="*60)

category_sales = data.groupby("Category")["Total_Sales"].sum()

print(category_sales)

'1 Chart (Bar Chart)'

category_sales = data.groupby("Category")["Total_Sales"].sum().sort_values()

plt.figure(figsize=(12, 6))

plt.bar(category_sales.index, category_sales.values)

plt.title("Category Wise Sales", fontsize=15, fontweight="bold")
plt.xlabel("Category")
plt.ylabel("Total Sales (₹)")

plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig("Images/category_sales.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("Category-wise total sales were calculated to identify the best-performing product categories.")

print("\n👀 Observation:")
print("Fashion recorded the highest sales (₹2.17M).")
print("Electronics was the second highest.")
print("Home generated the lowest sales.")

print("\n💡 Business Insight:")
print("Focus more on Fashion and Electronics, while improving marketing strategies for the Home category.")



'City Wise Sales Analysis'

print("\n" + "="*60)
print("City Wise Sales Analysis")
print("="*60)

city_sales = data.groupby("City")["Total_Sales"].sum().sort_values(ascending=False)

print(city_sales)

'2 Chart (Bar Chart)'

plt.figure(figsize=(12, 6))

plt.bar(city_sales.index, city_sales.values)

plt.title("City Wise Sales", fontsize=15, fontweight="bold")
plt.xlabel("\nCity")
plt.ylabel("Total Sales (₹)")

plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig("Images/city_sales.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("City-wise sales analysis was performed to identify the highest and lowest revenue-generating cities.")

print("\n👀 Observation:")
print("Pune generated the highest sales (₹1,314,346.25).")
print("Delhi and Lucknow were the second and third highest revenue-generating cities.")
print("Mumbai recorded the lowest sales (₹885,528.05).")

print("\n💡 Business Insight:")
print("Increase marketing efforts and maintain inventory in Pune, as it is the best-performing city.")
print("Investigate the reasons for Mumbai's lower sales and introduce targeted promotional campaigns to improve performance.")



'Product Wise Sales'

print("\n" + "="*60)
print("Product Wise Sales")
print("="*60)

product_sales = data.groupby("Product")["Total_Sales"].sum().sort_values(ascending=True)

print(product_sales)

'3 Chart (Bar Chart)'

plt.figure(figsize=(12,6))

product_sales.plot(kind="bar")

plt.title("Product Wise Sales", fontsize=15, fontweight="bold")
plt.xlabel("Product")
plt.ylabel("Total Sales")

plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig("Images/product_sales.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("This analysis evaluates the total sales generated by each product.") 
print("By grouping sales by product, we can identify which products contribute the most revenue and which products have lower demand.")

print("\n👀 Observation:")
print("The highest-selling product is Mixer.")
print("The lowest-selling product is Chair.")
print("Sales are not evenly distributed across products.")
print("A few products contribute a significant share of the total sales, while others generate comparatively lower revenue.")

print("\n💡 Business Insight:")
print("Continue promoting and maintaining inventory for the top-performing products to maximize revenue.")
print("Analyze the reasons behind the low sales of underperforming products. Possible factors include pricing, marketing, customer preferences, or seasonal demand.")
print("Consider running promotional campaigns or offering discounts on low-selling products to improve their performance.")
print("Use these insights for better inventory planning and demand forecasting, reducing the risk of stock shortages and excess inventory.")



'Monthly Sales Trend'

print("\n" + "="*60)
print("Monthly Sales Trend")
print("="*60)

data["Order_Date"] = pd.to_datetime(data["Order_Date"])
data["Month"] =  data["Order_Date"].dt.month_name()


month_order = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]

monthly_sales = (
    data.groupby("Month")["Total_Sales"]
    .sum()
    .reindex(month_order)
)

print(monthly_sales)

'4 Chart (Line Chart)'

plt.figure(figsize=(12, 6))

plt.plot(
    monthly_sales.index,
    monthly_sales.values,
    marker='o',
    linestyle='-',
    linewidth=2.5,
    color='royalblue'
)

plt.title("Monthly Sales Trend", fontsize=16, fontweight='bold')
plt.xlabel("Month", fontsize=12)
plt.ylabel("Total Sales", fontsize=12)

plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.savefig("Images/monthly_sales.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("This analysis shows how total sales change from month to month and helps identify sales trends throughout the year.")

print("\n👀 Observation:")
print("Sales peaked in May.")
print("Lowest sales were recorded in September.")

print("\n💡 Business Insight:")
print("Focus marketing during low-sales months.")
print("Maintain sufficient stock for high-sales months.")



'Payment Method Analysis'

print("\n" + "="*60)
print("Payment Method Analysis")
print("="*60)

payment_sales = (
    data.groupby("Payment_Method")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print(payment_sales)

" 5 Chart (Bar Chart)"

plt.figure(figsize=(12, 6))
payment_sales.plot(kind="bar")

plt.title("Payment Method Analysis", fontsize=16, fontweight="bold")
plt.xlabel("Payment Method")
plt.ylabel("Total Sales")

plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("Images/payment_method.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("This analysis shows the contribution of each payment method to total sales and highlights customer payment preferences.")

print("\n👀 Observation:")
print("Cash is the most preferred payment method.")
print("Card is the least preferred payment method.")

print("\n💡 Business Insight:")
print("Promote the most-used payment method for a smoother customer experience.")
print("Offer discounts or cashback on less-used payment methods to encourage adoption.")



'Gender Analysis'

print("\n" + "="*60)
print("Gender Analysis")
print("="*60)

gender_sales = (
    data.groupby("Gender")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print(gender_sales)

'6 Chart (Bar Chart)'

plt.figure(figsize=(12, 6))
gender_sales.plot(kind="bar")

plt.title("Gender Analysis", fontsize=16, fontweight="bold")
plt.xlabel("Gender", fontsize=12)
plt.ylabel("Total Sales", fontsize=12)

plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("Images/gender_analysis.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("This analysis compares the total sales generated by male and female customers to understand their purchasing contribution.")

print("\n👀 Observation:")
print("Male customers generated higher sales.")
print("Female customers generated lower sales.")

print("\n💡 Business Insight:")
print("Focus marketing campaigns on the higher-contributing customer segment.")
print("Design targeted offers to increase sales from the lower-contributing segment.")



'Rating Analysis'

print("\n" + "="*60)
print("Rating Analysis")
print("="*60)

rating_count = data["Rating"].value_counts().sort_index()

print(rating_count)

'7 Chart (Bar Chart)'

plt.figure(figsize=(12,5))

rating_count.plot(
    kind="bar"
)

plt.title("Rating Analysis", fontsize=16, fontweight="bold")
plt.xlabel("Rating", fontsize=12)
plt.ylabel("Number of Customers", fontsize=12)

plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("Images/rating_analysis.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("This analysis shows the distribution of customer ratings and helps measure overall customer satisfaction.")

print("\n👀 Observation:")
print("Most customers gave a 3-star rating (396 ratings).")
print("5-star ratings were the least common (181 ratings).")

print("\n💡 Business Insight:")
print("Maintain the factors driving high customer ratings.")
print("Analyze customer feedback for low ratings and improve service quality.")



'Correlation Heatmap'
numeric_data = data[[
    "Age",
    "Quantity",
    "Price",
    "Discount",
    "Total_Sales",
    "Rating"
]]

# Create Correlation Matrix

correlation = numeric_data.corr()

print(correlation)

'8 Chart (correlation Heatmap)'

plt.figure(figsize=(12,6))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    linewidths=0.5
)

plt.title("Correlation Heatmap", fontsize=16, fontweight="bold")

plt.tight_layout()
plt.savefig("Images/correlation_heatmap.png", dpi=300)
plt.show()

print("\n📊 Analysis:")
print("This heatmap shows the strength and direction of relationships between the numerical variables in the dataset.")

print("\n👀 Observation:")
print("Price has the strongest positive correlation with Total_Sales (0.69).")
print("Quantity also has a strong positive correlation with Total_Sales (0.61).")
print("Discount has a weak negative correlation with Total_Sales (-0.12).")
print("Age and Rating have very weak correlations with the other variables.")

print("\n💡 Business Insight:")
print("Variables with a strong positive correlation can be used to improve sales forecasting.")
print("Weak correlations indicate that other factors may influence customer behavior and should be explored further.")



'🚀 Final Business Insights'

print("\n" + "="*60)
print("Final Business Insights")
print("="*60)


print("\n📌 1. Product Performance")
print("Top-selling products contributed the highest share of total sales and should be prioritized for inventory and promotions.")

print("\n📌 2. Monthly Sales Trend")
print("Sales varied across different months, indicating seasonal demand patterns that can help with inventory planning.")

print("\n📌 3. Payment Method")
print("One payment method was used more frequently than others, showing customer preference for that payment option.")

print("\n📌 4. Customer Demographics")
print("One gender contributed more to total sales, which can help in designing targeted marketing campaigns.")

print("\n📌 5. Customer Ratings")
print("Most customers gave a 3-star rating, indicating moderate customer satisfaction and room for improvement.")

print("\n📌 6. Correlation Analysis")
print("- Price and Total Sales showed a strong positive relationship.")
print("- Quantity and Total Sales also showed a positive relationship.")
print("- Discount had a weak negative relationship with Total Sales.")

print("\n📌 7. Business Recommendations")
print("- Maintain sufficient stock of high-selling products.")
print("- Plan marketing campaigns around high-sales months.")
print("- Improve customer experience to increase 4-star and 5-star ratings.")
print("- Review the discount strategy since discounts had little impact on overall sales.")

print("\n🎯 Overall Conclusion")

print("- The EDA identified customer purchasing patterns, product performance, seasonal sales trends, payment preferences, customer ratings, and relationships between numerical variables.")
print("These insights can help the business improve inventory management, marketing strategies, and customer satisfaction while supporting data-driven decision-making.")


print("\n" + "="*60)
print("\nRetail Sales EDA Project Completed Successfully")
